services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - static
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal
    env_file:
      - .env

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    networks:
      - internal
    env_file:
      - .env

  vsftpd:
    build: ./requirements/bonus/vsftpd
    container_name: vsftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress_data:/home/ftpuser
    networks:
      internal:
        ipv4_address: 172.18.0.5
    env_file:
      - .env

  static:
    build: ./requirements/bonus/static
    container_name: static
    networks:
      - internal

volumes:
  wordpress_data:
  mariadb_data:

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

